### ISSUE TITLE
Posible bug en especialista:atender/2

### ISSUE THREAD

**Issue by Minimuino** [lauramcastro/practicas-VVS#1]
En el fichero especialista_test.erl fallan algunas pruebas. Concretamente, siempre que se hace un ?assert después de haber llamado a especialista:atender/2, salta un time out y el test no se llega a realizar. Además, la tarea tampoco se completa.

    ======================== EUnit ========================
    module 'especialista_test'
      especialista_test:40: disponible_recibir_test_...ok
      especialista_test:48: disponible_atender_test_...ok
      especialista_test:49: disponible_atender_test_...ok
      especialista_test:58: ocupado_recibir_test_...ok
      especialista_test:67: ocupado_atender_1_test_...ok
      especialista_test:68: ocupado_atender_1_test_...
    =ERROR REPORT==== 5-May-2015::16:43:10 ===
    Error in process <0.57.0> with exit value: {{case_clause,{primos,<0.55.0>}},[{cliente,loop,1,[{file,"src/cliente.erl"},{line,78}]}]}

    *timed out*
      undefined
    especialista_test:77: ocupado_atender_2_test_...
    =ERROR REPORT==== 5-May-2015::16:43:15 ===
    Error in process <0.64.0> with exit value: {{case_clause,{primos,<0.62.0>}},[{cliente,loop,1,[{file,"src/cliente.erl"},{line,78}]}]}

    ok
    especialista_test:78: ocupado_atender_2_test_...*timed out*
    undefined

    =ERROR REPORT==== 5-May-2015::16:43:20 ===
    Error in process <0.71.0> with exit value: {{case_clause,{primos,<0.69.0>}},[{cliente,loop,1,[{file,"src/cliente.erl"},{line,78}]}]}

    especialista_test:88: saturado_recibir_1_test_...*timed out*
    undefined

    =ERROR REPORT==== 5-May-2015::16:43:25 ===
    Error in process <0.77.0> with exit value: {{case_clause,{primos,<0.75.0>}},[{cliente,loop,1,[{file,"src/cliente.erl"},{line,78}]}]}

    especialista_test:99: saturado_atender_1_test_...ok
    especialista_test:100: saturado_atender_1_test_...*timed out*
    undefined
    [done in 20.047 s]
    =======================================================
      Failed: 0.  Skipped: 0.  Passed: 7.
    One or more tests were cancelled.
    error

Esto puede ser debido a mi escasa experiencia con eunit :P, pero creo que también podría ser un bug.

**Comment by lauramcastro** [comment]
Enhorabuena por encontrar los 3 primeros bugs con este módulo de pruebas, @Minimuino.

Como podéis ver, los dos primeros problemas tenían que ver con un error muy habitual en Erlang (y en lenguajes funcionales en general, relacionado con el uso de listas o el paso de argumentos como listas correcta o erróneamente).

El tercer problema no era trivial, y venía dado porque las pruebas ocupado_atender_2_test_/0, saturado_recibir_1_test_/0 y saturado_atender_1_test_/0 invocaban a especialista:recibir/1 esperando recibir "false", pero no llegaban a obtener nunca nada salvo un timeout en su lugar.

Lo que ocurría es que, ocupado calculando primos hasta 3000000, el especialista aún no había cambiado de estado desde "ocupado" (ni a "libre" ni a "saturado"), por tanto no era capaz de responder otros mensajes. En esas circunstancias, la llamada a gen_fsm:send_sync_event/2 de la línea 43 del módulo especialista fallaba con un timeout.

El parche actual "corrige" eso utilizando otra variante: gen_fsm:send_sync_event/3 que permite decidir cuánto esperar por la respuesta (en este caso, un máximo de 500 ms) antes de "fallar". En ese caso, el "fallo" se captura y se cambia por un simple false.

¿Quién puede decirme pros y contras de este parche?

**Comment by Minimuino** [comment]
No comprendo el código en Erlang al 100%, pero creo que entiendo su funcionamiento en líneas generales. En principio no le veo ningún inconveniente a este parche. Aunque ahora recibir/1 devuelva siempre "false" cuando el especialista tarda más de 500 ms, creo que es correcto. Según la especificación, un especialista ocupado siempre responde a recibir/1 con "false". Y cuando está realizando una tarea, está ocupado. Si el tiempo de tolerancia del especialista es mayor que 500 ms, y cuando termine la tarea cambia a disponible, responderá "true" cuando se llame a recibir/1 de nuevo.

**Comment by lauramcastro** [comment]
La intención no es que analizáseis el código de la solución, sino la solución en sí.

Efectivamente, la ventaja es que ahora siempre tenemos una respuesta (false) cuando el especialista está ocupado, ya sea porque no ha terminado la tarea, ya sea porque la ha terminado y se ha puesto en estado saturado. Además, en ambos casos volveremos a tener respuesta positiva (true) cuando el especialista termine y/o se des-sature (y se ponga en estado disponible de nuevo).

¿Alguna desventaja?
