### ISSUE TITLE
Error con la busqueda de contenidos

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#10]
Al realizar busquedas sobre los contenidos en ciertos casos no devuelve los resultados esperados. Por ejemplo, al realizar una busqueda con "Lavigne Avril" no encuetra contenido alguno cuando deberia encontrar uno.
Se adjunta un fichero de texto con pruebas hechas manualmente que prueban el funcionamiento de la funcionalidad y un fichero java con dichas pruebas implementadas en junit.

[ContenidoTest.java.txt](https://github.com/lauramcastro/practicas-VVS/files/161701/ContenidoTest.java.txt)
[pruebaBuscarContenido.txt](https://github.com/lauramcastro/practicas-VVS/files/161702/pruebaBuscarContenido.txt)

**Comment by lauramcastro** [comment]
Enhorabuena, como podéis comprobar tras el commit cfc7e4d24d7de1eac8e2e9d1ebe5bdae3bd8f837, habéis encontrado los dos primeros bugs. En concreto, la búsqueda con palabras desordenadas, y la búsqueda con trailing spaces (como podéis ver en travis: https://travis-ci.org/lauramcastro/practicas-VVS/builds/114472992, aunque el status final de ejecución no marca la build como fallida, tengo que revisar eso). Voy a cerrar este issue, ya que la manera correcta de proceder, ahora que ya tenemos las pruebas ejecutándose correctamente, es abrir un issue por cada bug individual. Por tanto, espero que abráis dos issues, uno para cada bug que habéis encontrado, haciendo referencia al test concreto que identifica cada uno.

**Comment by lauramcastro** [comment]
Por cierto, incorporad también como pruebas JUnit el resto de casos que teníais en el fichero de texto y no os dio tiempo a codificar; de surgir nuevos errores con esos nuevos casos, proceded de la manera indicada.
