### ISSUE TITLE
Especificación sobre almacén restringido

### ISSUE THREAD

**Issue by hmiacatracha** [lauramcastro/practicas-VVS#11]
Especificación de almacén restringido:
- Leyendo las funcionalidades del sistema, vemos que hace referencia a almacenes pero NO especifica el  almacén restringido.

-  Al observar el diagrama de clases:
1.- Para convertirse en un almacén restringido debe de pasarse como parámetro un almacén un almacén real.
2.- El almacén restringido tiene una serie de atributos (_timestamp, _busquedas, _minutos, _busquedasDisponibles).

Debido a la poca información sobre un almacén restringido, **Nos gustaría conocer la especificación del almacén restringido.**

**Comment by lauramcastro** [comment]
¡Excelente!

Durante la construcción de este sistema, se plantea la necesidad de poder restringir las búsquedas realizadas en cualquier Almacén dado a un número determinado; superada esa cantidad de búsquedas, el Almacén restringido debe rechazar más peticiones al método buscar hasta que no transcurra un cierto tiempo.

Esta funcionalidad se implementa utilizando un patrón Proxy, implementado por la clase AlmacenRestringido. Dicho proxy recibe la información necesaria para implementar el comportamiento arriba descrito (busquedas, minutos); los otros atributos que mencionáis se utilizan internamente también para implementar el comportamiento arriba descrito (o intentarlo ;-)).

Añado esta descripción al README, y cierro esta issue.
