### ISSUE TITLE
Error búsqueda con trailling spaces

### ISSUE THREAD

**Issue by fragmentados** [lauramcastro/practicas-VVS#12]
Los espacios en blanco introducidos en la búsqueda de contenidos son considerados como un caracter más de la palabra. 
Por ejemplo: Al buscar en un almacén " Avril ", debería encontrar un resultado pero no encuentra ninguno.

**Comment by lauramcastro** [comment]
Por ejemplo: este fallo ha sido revelado en la prueba https://github.com/lauramcastro/practicas-VVS/blob/0f383ee14711e96b48b11b354557bc7920b41409/test/contenido/ArchivoAudioTest.java#L41

**Comment by BreixoCF** [comment]
Con los cambios realizados en las pruebas del issue #13 debería arreglarse también los problemas de mutaciones de código para esta issue.

https://github.com/lauramcastro/practicas-VVS/commit/30727ad43eb79e44bf838822827ef7f179542845

Pendiente de confirmación.

**Comment by lauramcastro** [comment]
Aplicad los mismos comentarios de mejora de los `asserts` que os hago en el issue #13 y podéis cerrar ambos después.

**Comment by BreixoCF** [comment]
Realizados los cambios indicados respecto a `assert`
