### ISSUE TITLE
Erro de búsqueda con palabras desordenadas

### ISSUE THREAD

**Issue by BreixoCF** [lauramcastro/practicas-VVS#13]
Se facemos búsquedas de contidos nun almacén, poñendo as palabras en orden distinto a como está gardado na aplicación, o resultado non é o esperado.

Por exemplo, se facemos unha consulta cas palabras "lavigne avril", o resultado é que non atopa ningún contido. Sen embargo, se buscamos "avril lavigne", a búsqueda é exitosa.

**Comment by lauramcastro** [comment]
Para que la issue quede completa: indicadme fichero+función de la prueba que falla asociada a este bug.

**Comment by lauramcastro** [comment]
Por ejemplo: este fallo ha sido revelado en la prueba https://github.com/lauramcastro/practicas-VVS/blob/0f383ee14711e96b48b11b354557bc7920b41409/test/contenido/ArchivoAudioTest.java#L20

**Comment by BreixoCF** [comment]
Reabrimos el issue porque los test están realizados sin evitar "mutaciones de código".

Pendiente de hacer las modificaciones para evitar dichas mutaciones y realizar más pruebas para añadir más cobertura en un futuro.

**Comment by BreixoCF** [comment]
Modificaciones para evitar mutaciones de código realizadas en el siguiente commit:

https://github.com/lauramcastro/practicas-VVS/commit/30727ad43eb79e44bf838822827ef7f179542845

Pendiente de cierre o de corregir las modificaciones.

**Comment by lauramcastro** [comment]
Como mejora, en lugar de usar `assertEquals(false, X)`, recordad que hay más métodos en el API de JUnit y usad los adecuados, en este caso `assertFalse(X)` (también hay algun `assertEquals(true, X)` que podría ser simplemente `assert(X)`).

**Comment by BreixoCF** [comment]
Realizados lo cambios indicados con respecto a `assert`
