### ISSUE TITLE
Proveedor almacen

### ISSUE THREAD

**Issue by hmiacatracha** [lauramcastro/practicas-VVS#14]
En la clase ProveedorAlmacen cuando estableces estableces un proveedor por ejemplo:
 **Almacen proveedor = new ProveedorAlmacen(almacenRestringido, almacenReal);**

Allí estamos estableciendo un almacén restringido el almacén real. Cuando hago **proveedor.buscar("cancion")** en los test dos veces (el numero de búsquedas especificados en el almacenRestringido), por lo que yo entiendo viendo el diagrama:

  - Debería de devolver una excepción cuando rebasa el número máximo de búsquedas
 

-  Sin embargo:  Sigue realizando la búsquedas sin ningún problema.

**Comment by lauramcastro** [comment]
En el ejemplo que pones, `almacenRestringido` es el almacén "base" y `almacenReal` es el proveedor al que se recurre si las búsquedas en el almacén "base" resultasen vacías. 

Con esta configuración, sólo se preguntaría al `almacenReal` si `almacenRestringido` no tiene ningún contenido que responda a la búsqueda, no si la búsqueda devuelve una excepción por haber superado el límite de consultas permitidas.

El comportamiento anómalo al que te refieres (un almacén restringido que no restringe y permite seguir buscando)... ¿está en algún test implementado? Si es así, referenciadlo en la issue como comenté en las issues #12 y #13. Si cuando está "solo" lo hace bien pero cuando está decorado con un proveedor es cuando lo hace mal, también referenciad la prueba que lo muestra.

Aprovecho para recordaros que podéis implementar escenarios de prueba negativos (ahora que ya sabemos que una prueba negativa es la que comprueba un comportamiento coherente en caso de error) donde lo que comprobéis es que, efectivamente, se lanza una determinada excepción. En caso de no lanzarse, esa prueba debería fallar.

**Comment by AdriGL** [comment]
En este commit [https://github.com/lauramcastro/practicas-VVS/commit/334c849e27a5da9e2bf326a915ce06c7cccada82](url) se han implementado los tests que comprueban que un almacenRestringido funciona correctamente aunque este decorado como proveedor

**Comment by lauramcastro** [comment]
Entiendo que, ya que las pruebas pasan, no existía bug. Cierro la issue, aunque podéis solicitar que se reabra si no es así.
