### ISSUE TITLE
Especificación de RegistroAlmacen

### ISSUE THREAD

**Issue by hmiacatracha** [lauramcastro/practicas-VVS#15]
He observado en el diagrama de clases y por lo que veo **RegistroAlmacen** sobrescribe el método buscar. He leído en el _README_ y veo que **no dice nada sobre que funcionalidad específica** que tiene que realizar en el método **buscar** en un ResgistroAlmacen.

 **Te importaría poder especificarlo, porfavor**

**Comment by lauramcastro** [comment]
Listo. De momento voy a dejar esta issue abierta... porque probablemente nos venga bien ;-).

**Comment by AdriGL** [comment]
De acuerdo a la especificación que diste en el commit 7bffa63, hemos intentado hacer las pruebas sobre el método buscar de un RegistroAlmacen, pero nos hemos encontrado con el problema de que no sabemos como probar el registro por la salida estándar. Por lo tanto, la prueba esta incompleta:
 https://github.com/lauramcastro/practicas-VVS/blob/37e62f3c48f1222a90cfc04b05a32b6369f112aa/test/almacen/RegistroAlmacenTest.java#L114

**Comment by lauramcastro** [comment]
Como ya comentamos en clase, no es buena idea hacer entrada/salida estándar si se puede evitar (esto es, salvo que el software _deba_ ser interactivo), ya que lo convierte en difícil de probar. El commit  1bce1d5 hace que `RegistroAlmacen` vuelque su información en un fichero de log llamado `<nombreAlmacen>-registro-<timestamp>.log`.
