### ISSUE TITLE
Bug al agregar contenido nulo a un AlmacenReal

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#18]
Hemos realizado el siguiente test: Añadir contenido nulo a un almacén real (agregarContenidoNullTest())
Nosotros esperábamos que no añadiera contenidos nulos al almacén,**sin embargo, se añadió sin ningún problema** tal y como observamos https://github.com/lauramcastro/practicas-VVS/blob/6e028b2065254d3797af6c8b1898fc24b209ebf1/test/almacen/AlmacenRealTest.java#L88

**Comment by lauramcastro** [comment]
Bien hecho. El commit f818ec0 de la rama `ant` y el commit  5587bc5 de la rama `maven` corrigen este error de la manera en la que se especifica en el README. Debéis actualizar la prueba para reflejar este comportamiento (y también otra prueba en `AlmacenRestringidoTest`, que no es coherente con ésta y que antes pasaba -cuando no debía- y ahora falla), y cuando lo hagáis podéis entonces cerrar la _issue_.

A partir de este momento, la rama `ant` se considera `deprecated` y se mantiene por razones de documentación; trabajaremos contra la rama `maven` (usad por favor ramas locales para evitar conflictos a la hora de hacer `pull`).

**Comment by BreixoCF** [comment]
Ahora mismo, al ejecutar las pruebas fallan varios de las pruebas (agregarContenidoNullTest y obtenerContenidosTest) deteniendo la ejecución de las demás pruebas.

**Comment by lauramcastro** [comment]
No, la ejecución de pruebas no se detiene al encontrar el primer error, continúa con el resto de pruebas.

**Comment by BreixoCF** [comment]
Ah perdón, tarda más de lo normal, y pensaba que se quedaba parada la ejecución de las pruebas. Aún así, esos dos siguen dando error. Perdón por la confusión. :(

**Comment by lauramcastro** [comment]
Sí, de momento hay (sólo) una prueba que tarda cosa de un minuto porque comprueba cosas que tienen que ver con la limitación de peticiones a almacenes :-). ¡En algún momento espero que haya más pruebas no funcionales! (guiño, guiño)

**Comment by AdriGL** [comment]
El commit  d4cd9cc arregla los fallos en los tests de las clases almacenRealTest y almacenRestringidoTest, ahora ya deberían de pasar todas las pruebas. Abro un issue nuevo en el que se refleje la necesidad de cambiar los tests de almacenRestringidoTest a tests mas simples y que prueben valores frontera, tal y como se hizo para el almacenRealTest.
