### ISSUE TITLE
Duda al crear prueba de AlmacenReal

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#19]
No sabemos como implementar este test: https://github.com/lauramcastro/practicas-VVS/blob/6e028b2065254d3797af6c8b1898fc24b209ebf1/test/almacen/AlmacenRealTest.java#L283

En la especificación no se define como debe de actuar un almacén real cuando se intenta establecer proveedor, por lo que no sabemos como implementar la prueba.

**Comment by lauramcastro** [comment]
Esta issue está relacionada con las issues #8 y #9, y me hace darme cuenta de que realmente la #9 no tuvo una adecuada respuesta. En ese caso preguntábais si un almacén (que pueda tener proveedor) puede ser proveedor de sí mismo, y no os respondí a eso. Efectivamente, ni la especificación ni la implementación lo controlan, por lo que deberíais poder crear una prueba que demuestre el problema que esto puede acarrear. Voy a reabrir la issue #9 como bug, asignada a vosotros pendiente de que implementéis la prueba demostradora.

Ahora, respondiendo a la pregunta que formuláis aquí, como ya os decía en la issue #8 sólo van a tener comportamiento relacionado con los proveedores los almacenes decorados con un ProveedorAlmacen. Para el resto, las operaciones relacionadas no deben producir cambio de comportamiento ni cambio de estado alguno (de ahí las pistas para las pruebas que deben verificar esto).
