### ISSUE TITLE
Detectado bug en módulo especialista

### ISSUE THREAD

**Issue by Minimuino** [lauramcastro/practicas-VVS#2]
Ajustando un poco el tamaño de la tarea de encontrar primos y analizando los tiempos, he visto que el especialista no devuelve "false" al pasar a saturado. Adjunto los resultados para mostrar el error:

    2> eunit:test(especialista_test, [verbose]).
    ======================== EUnit ========================
    module 'especialista_test'
      especialista_test:31: disponible_recibir_test_...ok
      especialista_test:39: disponible_atender_test_...ok
      especialista_test:40: disponible_atender_test_...ok
      especialista_test:49: ocupado_recibir_test_...ok
      especialista_test:58: ocupado_atender_1_test_...ok
      especialista_test:59: ocupado_atender_1_test_...[0.041 s] ok
      especialista_test:68: ocupado_atender_2_test_...ok
      especialista_test:69: ocupado_atender_2_test_...[0.500 s] ok
      especialista_test:79: saturado_recibir_1_test_...*failed*
    in function especialista_test:'-saturado_recibir_1_test_/0-fun-2-'/2 (test/unidad/especialistas    /especialista_test.erl, line 79)
    **error:{assertEqual_failed,[{module,especialista_test},
                         {line,79},
                         {expression,"especialista : recibir ( Esp )"},
                         {expected,false},
                         {value,true}]}

      especialista_test:90: saturado_atender_1_test_...ok
      especialista_test:91: saturado_atender_1_test_...[0.502 s] ok
      [done in 1.121 s]
    =======================================================
      Failed: 1.  Skipped: 0.  Passed: 10.

El fallo se observa en los casos ocupado_atender_1 y saturado_recibir_1. Ambos utilizan un especialista con tolerancia = 1 ms y una tarea primos < 9000. Sin embargo, vemos que el test ocupado_atender_1 no falla a pesar de que tarda 41 ms en completarse. Espera recibir "true" y, en efecto, recibe "true", pero el funcionamiento correcto sería recibir "false". Sé que lo adecuado sería haber hecho un assert negativo, pero lo dejé así para poder ver el tiempo que se invierte en completar la tarea. 

En el caso de saturado_recibir_1, vemos que falla porque espera "false", es decir, que el especialista esté saturado. Se trata del caso contrario al anterior, y es igualmente incorrecto. En los casos saturado_atender_1 y ocupado_atender_2 el valor de retorno es el correcto sólo porque el parche anterior lo corrige (ya que tardan más de 500 ms) devolviendo siempre "false". El error ya debía estar en la primera versión de la implementación.

**Comment by lauramcastro** [comment]
Enhorabuena de nuevo por revelar uno de los problemas más habituales en sistemas asíncronos (prometo de nuevo que no fue a propósito ;-)) y que, a pesar de lo que pudiera parecer, el verdadero problema no estaba presente en la anterior versión de la implementación porque era consecuencia directa de usar el envío síncrono con timeout.

El diagnóstico que haces es un poco incorrecto porque el cálculo de la saturación es un poco más complejo, no es simplemente 41 > 1 y por tanto se satura (si no, se saturaría muy fácilmente). Podéis consultar la línea 97 del fichero especialista.erl para ver cómo se calcula realmente la saturación.

No obstante, es cierto que el especialista parecía bloquearse cuando no debería, aún cuando la tarea no llegase a durar suficiente para saturarlo y por tanto esperaríamos que el recibir nos devolviera true. Esto ocurría si se le invocaba a recibir mientras estaba ocupado. En ese caso, el parche anterior (al issue #1), introdujo una variante inesperada.

El error estuvo, por mi parte, en considerar que el envío asíncrono con timeout *desistiría* del envío del mensaje al proceso Especialista que está ocupado trabajando y no puede responder. Pero no es así: el timeout permite devolver un valor a quien invoca la operación con un retardo máximo (se garantiza que el bloqueo dura como máximo el timeout), pero no significa que la petición no se haya enviado al Especialista. De hecho, el mensaje queda en su buzón y al terminar la tarea, pasaba a procesarlo. Inmediatamente, volvía a ponerse ocupado como consecuencia del mensaje "recibir" que tenía pendiente de responder (aunque el timeout ya hubiera generado una respuesta al invocador).

El parche soluciona el problema modificando ligeramente la especificación para que sea compatible con que los procesos tengan que reaccionar a esos mensajes que les han llegado cuando estaban ocupados y por los que nadie espera ya respuesta (porque actuó el timeout). La incoherencia se elimina de este modo:

- en estado disponible, recibir devuelve siempre true (indica disponibilidad) y ya no provoca el cambio de estado a ocupado
- en estado disponible, ahora la invocación a atender desenvoca en un cambio de estado y una auto-llamada a atender (una vez en ocupado) para atender la petición que se acaba de recibir

La modificación en el código está subida al repositorio, así como la actualización de los diagramas. No he actualizado las pruebas (la prueba ocupado_recibir_test del módulo especialista_test ahora falla, pero es incorrecta con esta nueva especificación).

**Comment by Minimuino** [comment]
Perfecto, actualizaré las pruebas en cuanto pueda para adaptarlas a la nueva especificación.
