### ISSUE TITLE
Bug: Duración de los archivos de audio

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#23]
Al crear un archivo de audio con una duración negativa el archivo se crea correctamente y al obtener esta tambien devuelve dicho valor negativo. 

https://github.com/lauramcastro/practicas-VVS/commit/df74be63359288de64317135b0ba5e9e923613a0/src/test/java/vvs/contenido/ArchivoAudioTest.java#L90

**Comment by BreixoCF** [comment]
Eso xa o comentáramos en clase, que llo había preguntado eu cando fixéramos os test.

**Comment by lauramcastro** [comment]
Bien, para poder considerar esto un _bug_ y por tanto hacer que la prueba falle para demostrar que la implementación debe corregirse, debemos aclarar la especificación. ¿Qué creéis que debería pasar cuando se intenta crear un `Contenido` con duración negativa?

**Comment by BreixoCF** [comment]
Que saltara un mensaje de error (excepción), decindo que non se pode crear `Contenido` con duración negativa

**Comment by lauramcastro** [comment]
Bien, no existen excepciones en el paquete contenido, pero el commit 8d26453830798fd5a15837afe6394cebed0abe03 añade una genérica que podéis utilizar en la prueba. Actualizo la especificación, y quedo a la espera de la prueba fallida para actualizar la implementación.

**Comment by dvdtr87** [comment]
Actualizado el test para usar la excepcion genérica.

**Comment by lauramcastro** [comment]
@AdriGL @BreixoCF @Cryx7 @dvdtr87 @fragmentados @hmiacatracha :  La resolución de este _bug_ nos trae una de las consecuencias que muestran el esfuerzo de mantenimiento que requieren las pruebas dentro de un proyecto software. El cambio en la implementación que representa el commit c595665 es mínimo, pero ahora muchas de las pruebas deberán ser actualizadas, ya que la creación de objetos `ArchivoAudio` requiere capturar una excepción, y por tanto no se puede hacer _inline_ en la declaración de atributos de la clase. Os obligará a usar métodos de "_setup_" en JUnit (a través de sus [_fixtures_](https://github.com/junit-team/junit4/wiki/Test-fixtures)).

**Comment by BreixoCF** [comment]
Creo que xa está todo o código cos métodos de _setup_ de JUnit! @lauramcastro
