### ISSUE TITLE
Mutation test con pit

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#24]
He estado haciendo test con la herramienta de mutacin pit y en los tests de buscar de archivo de audio no encuentra ningún problema. En clase habías comentado que al solo comprobar el tamaño de la lista devuelta podrían ser tests poco fiables pero, ¿ si aplicando la mutación no encuentra problema quiere decir que es correcto y no habría que modificar el test para comprobar que objeto devuelto es el buscado?

**Comment by lauramcastro** [comment]
Que esa herramienta de mutación en concreto no encuentre el problema, naturalmente, no quiere decir que el problema no exista :-). Recordad que ninguna técnica es infalible, y en este caso concreto sabríamos aplicar inserción de errores (manual) para revelar el problema, como comentamos en clase.
