### ISSUE TITLE
Busqueda en proveedor cuando tanto el almacen base como el proveedor tienen contenido.

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#25]
Cuando realizamos una búsqueda en un proveedor, según la especificación, si no se encuentra contenido en el almacén base, pasa a buscar al proveedor.

En un supuesto en el que hagas una búsqueda en la que tanto el almacén base como el proveedor tengan contenido que se ajuste a esa búsqueda, pero sea contenido **distinto**, según la especificación, solo se mostraría el contenido del almacén base, y así es como esta implementado en el código actualmente. ¿Es este el funcionamiento real que se quiere? ¿O se prefiere, aunque sea mas complejo, que en la búsqueda se muestren tanto los resultados del almacén base como los del proveedor, si son distintos?

**Comment by lauramcastro** [comment]
El comportamiento deseado es que sólo se recurra al proveedor si el almacén base no puede proporcionar ningún resultado. No se busca devolver los resultados más completos posibles a través de una cadena de almacenes, sino evitar no devolver ningún resultado teniendo una "segunda oportunidad", por así decirlo.
