### ISSUE TITLE
Establecer proveedor Null 

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#26]
Como podemos comprobar en este test: https://github.com/lauramcastro/practicas-VVS/blob/137fd25ef2f1477667586929ce44e3a313917d2c/src/test/java/vvs/almacen/ProveedorAlmacenTest.java#L236

Aunque no causa problemas de funcionamiento, se puede establecer como proveedor un null. ¿Se debería controlar para evitar futuros problemas?

**Comment by lauramcastro** [comment]
Utilizar un valor `null` como argumento para `establecerProveedor(Almacen)` es la única manera, dada la API que ofrece `Almacen`, de quitar un proveedor una vez que se ha puesto uno (para los almacenes apropiadamente decorados). Una posible mejora sería añadir al API un método `+eliminarProveedor()` que proporcionara esa funcionalidad (de nuevo, implementada únicamente en el decorador `ProveedorAlmacen`, claro), pero no vamos a implementarla en esta ocasión.

**Comment by lauramcastro** [comment]
Dicho lo anterior, lo adecuado sería tener en la suite de pruebas alguna(s) prueba(s) que validase que, efectivamente, utilizar `null` como argumento de `establecerProveedor` tiene el efecto esperado.
