### ISSUE TITLE
FindBugs: vvs.contenido.ArchivoAudio - BAD_PRACTICE

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#27]
El plugin findbugs encontró un error en la clase vvs.contenido.ArchivoAudio el método hashCode no ha sido redefinidio por lo que cualquier función que depende de esta funcionará de forma incorrecta.
[fidnBugs.pdf](https://github.com/lauramcastro/practicas-VVS/files/210624/fidnBugs.pdf)

**Comment by lauramcastro** [comment]
El commit d01675e4178aa33d3ebe7a2cafc1f711ac0c6335 también resuelve esta issue. Recordad que con la orden `mvn site` podéis obtener todos los informes que en el `pom.xml` se declaran en la sección `reporting`, que se consultan de forma agregada en `target/site/project-reports.html` (incluyendo el JavaDoc, etc.).
