### ISSUE TITLE
CheckStyle:  errores de estilo y malas prácticas

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#28]
Al ejecutar el plugin checkStyle se puede observar en el reporte que genera todos los errores de estilo y prácticas que se deberían evitar como por ejemplo el uso de "números mágicos", redundancia al declarar los métodos, etc.

[CheckStyle.pdf](https://github.com/lauramcastro/practicas-VVS/files/210637/CheckStyle.pdf)

**Comment by lauramcastro** [comment]
En el _commit_  33448bd se reducen a menos de una tercera parte los errores notificados por CheckStyle. Podéis comprobar que los que han dejado tienen que ver esencialmente con:
- parámetros que se reciben y no se modifican, por lo que CheckStyle recomienda que sean final
- en la misma línea del anterior criterio, métodos que no se sobreescriben (porque en la implementación actual no hay una subclase de esa clase) y no son vacíos ni abstractos, CheckStyle considera que deben ser siempre final
- coincidencias entre nombres de parámetros que se reciben y nombres de atributos de la clase; la ambigüedad está siempre resuelta gracias al uso de `this.`, pero como esto es fuente de errores, CheckStyle lo considera problemático

Además, hay alguna línea que sobrepasa mínimamente los 80 caracteres, pero que partirla sería menos legible (en mi opinión) y un par de "magic numbers" (cantidades fijas que se usan, en concreto, en dos métodos `hashCode()` y que no están declarados como constantes).

En estos términos, doy por cerrada esta _issue_.
