### ISSUE TITLE
PMD

### ISSUE THREAD

**Issue by dvdtr87** [lauramcastro/practicas-VVS#29]
El plugin PMD informa de que existen varias cosas que se podrían mejorar para obtener un codigo mas eficiente y claro, como por ejemplo el uso redundante de paréntesis o redifinir un método que simplemente llama al de la clase padre.

[PMD.pdf](https://github.com/lauramcastro/practicas-VVS/files/210646/PMD.pdf)

**Comment by lauramcastro** [comment]
Para el resto de personas de la clase que no se hayan ocupado de esta tarea, simplemente sabed que con `mvn pmd:pmd` podéis obtener el informe que adjunta @dvdtr87. Se genera en formato `HTML en target/site/pmd.html`.
