### ISSUE TITLE
Cifrado césar no permite todos los desplazamientos

### ISSUE THREAD

**Issue by rodarima** [lauramcastro/practicas-VVS#3]
Al tratar de ejecutar el cifrado con un desplazamiento múltiplo del tamaño del alfabeto:
OFFSET = LENGTH * K
Para K = 0, 1, ...
La tarea falla de forma inesperada. A continuación la traza en el intérprete:

erl -pa ebin             
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1>  l( cifrado_cesar).
{module,cifrado_cesar}
2> {T,P}=cifrado_cesar:programar(1, "ABC", "C", 0).
{cifrado_cesar,<0.36.0>}
3>  cifrado_cesar:do(P).

=ERROR REPORT==== 17-May-2015::20:03:17 ===
Error in process <0.36.0> with exit value: {function_clause,[{lists,nth,[0,[]],[{file,"lists.erl"},{line,168}]},{cifrado_cesar,encode,4,[{file,"src/cifrado_cesar.erl"},{line,98}]},{cifrado_cesar,loop,4,[{file,"src/cifrado_cesar.erl"},{line,81}]}]}

Se esperaba el resultado "C".

**Comment by lauramcastro** [comment]
Correcta detección del bug y correcto diagnóstico.

@rodarima : debes subir al repositorio una prueba de unidad que rompa en la versión actual, y que deberá pasar en cuanto yo suba el parche correspondiente.

**Comment by rodarima** [comment]
@lauramcastro: En el repositorio hay dos pruebas que deberían pasarse una vez solucionado el bug. Se encuentran en:

https://github.com/lauramcastro/practicas-VVS/blob/master/test/unidad/tareas/cifrado_cesar_test.erl#L86
https://github.com/lauramcastro/practicas-VVS/blob/master/test/unidad/tareas/cifrado_cesar_test.erl#L96

En concreto son los tests cifrado_cesar8_test_() y cifrado_cesar9_test_(). Para K = 1 y 0  respectivamente.

Sin embargo no "rompen" como test fallidos, si no que provocan un error de timeout, puesto que no llegan a recibir ninguna respuesta. Esta es la salida que provocan:

Error in process <0.76.0> with exit value: {function_clause,[{lists,nth,[0,"BCDEFGHIJKLMNÑOPQRSTUVWXYZ"],[{file,"lists.erl"},{line,168}]},{cifrado_cesar,encode,4,[{file,"src/cifrado_cesar.erl"},{line,98}]},{cifrado_cesar,loop,4,[{file,"src/cifrado_cesar.erl"},{line,81}]}]}

cifrado_cesar_test:91: cifrado_cesar8_test_...*timed out*
undefined

=ERROR REPORT==== 18-May-2015::21:30:52 ===
Error in process <0.81.0> with exit value: {function_clause,[{lists,nth,[0,"BCDEFGHIJKLMNÑOPQRSTUVWXYZ"],[{file,"lists.erl"},{line,168}]},{cifrado_cesar,encode,4,[{file,"src/cifrado_cesar.erl"},{line,98}]},{cifrado_cesar,loop,4,[{file,"src/cifrado_cesar.erl"},{line,81}]}]}

cifrado_cesar_test:101: cifrado_cesar9_test_...*timed out*
undefined
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 10.
One or more tests were cancelled.

**Comment by lauramcastro** [comment]
Después del commit 84457b807f61c8532879d0d804ac1f73cb2952a7 las pruebas `cifrado_cesar8_test_/0` y `cifrado_cesar9_test_/0` ya no dan timeout (ver issue #5) pero fallaban igualmente. El commit 08a6c0f4e4488b833bc85ffccd9c69f4185d9e64 soluciona este bug, debido a que no se contemplaba explícitamente el caso de los offset que provocan que la cadena cifrada sea exactamente la misma que la proporcionada.
