### ISSUE TITLE
GraphWalker - Problema con la configuración

### ISSUE THREAD

**Issue by BreixoCF** [lauramcastro/practicas-VVS#31]
Intentando executar os test de GraphWalker sáeme o seguinte erro:

```
breixocf@BreixoCF ~/Desktop/fic/4/VVS/practicas/laura 4 $ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building VVS 2015-2016: SpotiVVSy 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ SpotiVVSy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/breixocf/Desktop/fic/4/VVS/practicas/laura/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ SpotiVVSy ---
[INFO] Compiling 2 source files to /home/breixocf/Desktop/fic/4/VVS/practicas/laura/target/classes
[INFO] 
[INFO] --- graphwalker-maven-plugin:3.3.0:generate-test-sources (generate-test-sources) @ SpotiVVSy ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ SpotiVVSy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ SpotiVVSy ---
[INFO] Compiling 1 source file to /home/breixocf/Desktop/fic/4/VVS/practicas/laura/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/breixocf/Desktop/fic/4/VVS/practicas/laura/src/test/java/vvs/contenido/ColeccionGraphWalker.java:[9,70] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.645 s
[INFO] Finished at: 2016-04-29T01:32:55+02:00
[INFO] Final Memory: 17M/568M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:testCompile (default-testCompile) on project SpotiVVSy: Compilation failure
[ERROR] /home/breixocf/Desktop/fic/4/VVS/practicas/laura/src/test/java/vvs/contenido/ColeccionGraphWalker.java:[9,70] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Concretamente o cannot find symbol vén dado porque a clase ColeccionModel do .graphml non a detecta.
¿Que hai que facer para que o proxecto detecte o ColeccionModel.graphml? Supoño que así arranxarei ese problema.

**Comment by BreixoCF** [comment]
Esquecéuseme _linkar_ o commit: https://github.com/lauramcastro/practicas-VVS/commit/81ad328f8439abad9512129634cf30d44dd5f78b/src/test/java/vvs/contenido/ColeccionGraphWalker.java#L9

**Comment by lauramcastro** [comment]
O problema está en que o modelo está mal formado; antes de incorporar un modelo ao repositorio, asegurádevos de comprobar que o gráfico é válido executando:

`java -jar /O/VOSO/PATH/A/GRAPHWALKER/graphwalker.jar offline -m src/test/resources/vvs/contenido/ColeccionModel.graphml "random(edge_coverage(100))"`

Neste caso o resultado é:

```
When parsing model: 'src/test/resources/vvs/contenido/ColeccionModel.graphml' The string 'Start
INIT: numCont=0;' did not conform to GraphWalker syntax rules.
```

O problema está na secuencia `INIT: numCont=0;`, que debe ir no primeiro estado ao que se chega desde Start, pero non en Start (este estado non debe ter modificadores). Facendo este cambio, as probas con GraphWalker execútanse... e salta unha aserción, pero iso xa é traballo voso determinar se é un bug ou un problema na implementación da proba.

**Comment by BreixoCF** [comment]
Correxido o modelo, as probas con GraphWalker execútanse pero no meu caso éntrame nun bucle infinito do modelo que implementaches ti e non sei se as miñas se executan ou non. Falando con membros do outro grupo, pásalles o mesmo ó executar a súa proba.

```
13:23:18.603 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.603 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.603 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.603 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute agregarContenido
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute agregarContenido
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute establecerProveedor
13:23:18.604 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.605 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarProveedor
13:23:18.605 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.605 [main] DEBUG o.g.core.machine.ExecutionContext - Execute establecerProveedor
13:23:18.605 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.606 [main] DEBUG o.g.core.machine.ExecutionContext - Execute establecerProveedor
13:23:18.606 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.606 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.606 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.606 [main] DEBUG o.g.core.machine.ExecutionContext - Execute agregarContenido
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute establecerProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute ConProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.607 [main] DEBUG o.g.core.machine.ExecutionContext - Execute eliminarContenido
13:23:18.608 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.608 [main] DEBUG o.g.core.machine.ExecutionContext - Execute agregarContenido
13:23:18.608 [main] DEBUG o.g.core.machine.ExecutionContext - Execute SinProveedor
13:23:18.608 [main] DEBUG o.g.core.machine.ExecutionContext - Execute agregarContenido
```

**Comment by lauramcastro** [comment]
Pois atendede tod@s, @BreixoCF @AdriGL @Cryx7 @dvdtr87 @fragmentados @hmiacatracha : semella que demos cunha "limitación" de GraphWalker: **só permite máis dun modelo no proxecto se os modelos son pedazos dun modelo máis grande**, non modelos illados/independentes. Fixádevos no exemplo da [PetClinic da documentación](http://graphwalker.github.io/petclinic/).

O meu modelo `ProveedorAlmacen` e o de `AlmacenReal` sobre o que me consultaron Adrián e Heidy deberían ser doadamente combinables xa que os estados `AlmacenVacio` e `SinProveedor` poderían ser o mesmo. Para combinalos co modelo de colección de Breixo, tamén se poderían fundir ese estado `AlmacenVacioSinProveedor` con `ColeccionVacia`. Comprobade no exemplo cómo cando temos varios modelos para GraphWalker no repositorio, só un deles ten que ter estado inicial, e só a implementación desa interface ten a anotación `start = NomeDoEstadoInicial` (o resto de implementacións manteñen só a anotación da condición de terminación `value`). Comprobade tamén no exemplo como se usa a notación SHARED para indicar que estados son os compartidos.

Non contaba eu con este imprevisto, e a súa resolución require que traballedes ambos equipos xuntos. Se o conseguides facer, sen dúbida mereceredes a máxima nota de prácticas! :+1:

**Comment by BreixoCF** [comment]
Vale!! A miña dúbida é, ¿temos que facer un solo grafo que inclúa todo (Coleccion, ProveedorAlmacen e AlmacenReal) ou facer os tres pero que só un teña un inicio e os demais usen a anotación shared?

**Comment by lauramcastro** [comment]
A segunda opción: manter os sub-modelos, elixindo un para facer de raíz e "enlazándoos" a través da anotación SHARED (e adaptando as implementacións, claro).

**Comment by BreixoCF** [comment]
Cando poidas @lauramcastro , bótalle un ollo aos nosos grafos e se podes danos a túa opinión.

**Comment by lauramcastro** [comment]
O único que me suscita algunha dúbida é o sub-modelo en `AlmacenRestringidoModel`, xa que no estado `AlmacenConContenidoConBusquedas` boto de menos unha auto-transición a si mesmo coa operación `agregarContenido` que aumente `numCont`. Polo demais, simplemente sinalar que a parte de abaixo do modelo é "sumidoiro", é dicir, unha vez que vos quedades sen procuras (`numBusq == 0`) nunca podedes volver á parte de arriba do modelo, quedades para sempre nos estados `AlmacenCon/SinContenidosSinBusquedas`. Non estou segura de se iso é o que queredes.

O resto de modelos, moito máis sinxelos, semellan correctos!

**Comment by BreixoCF** [comment]
Eso é certo, pero non sabía como simular o tempo para restaurar o número de búsquedas a facer. Se hoxe estás no despacho, pásome a preguntar.

**Comment by lauramcastro** [comment]
Un xeito "creativo" de simular o tempo neste caso (a creatividade sempre é a vosa amiga cando se trata de _testing_) podería ser o seguinte: se en cada transición forzades a que transcorra certo tempo (por exemplo, facendo un `sleep` de 100 ms) entón a efectos prácticos podedes contabilizar non só o número de veces que buscades (`numBusq`) senón o "tempo acumulado" que ides facendo cada vez que transicionades, de xeito que podiades comprobar se se fai unha procura "antes de tempo", que falle.

**Comment by AdriGL** [comment]
Se ha implementado el paso del tiempo en el nuevo grafo, como se comento. Commit 3e035b4eaf9fb374d11ffe376e68045a4dcbc75d
