### ISSUE TITLE
Error debido al movimiento de la clase GeneradorContenido

### ISSUE THREAD

**Issue by fragmentados** [lauramcastro/practicas-VVS#32]
Al mover la clase GeneradorContenido a un nuevo paquete para una mayor organización de las clases, se genera un error en la build pese a que los tests son ejecutados sin fallos.
.

**Comment by AdriGL** [comment]
El error esta relacionado con Graphwalker, y como no queremos que travis de error, se ha optado por comentar el modelo del grafo que creemos que ocasiona el error, en el commit 5f99a684960847e9820090fa90c67d3f35b2e18c
