### ISSUE TITLE
Cifrado césar permite un alfabeto incorrecto

### ISSUE THREAD

**Issue by rodarima** [lauramcastro/practicas-VVS#4]
Un alfabeto es un conjunto de símbolos. Sin embargo para el cifrado césar es necesario que estos símbolos tengan un orden establecido. Esto se logra con el empleo de una lista de símbolos (cadena). 

De esta forma, es posible introducir "AAABC" como cadena, introduciendo símbolos duplicados.

No es adecuado introducir esta cadena, pues será aceptada como un alfabeto válido, esto es: { A, B, C }.

Al cifrar una cadena como "AB" con desplazamiento 1, el resultado esperado con ese alfabeto es:

BC

Sin embargo se obtiene AC, puesto que se ha desplazado la A, que se ha encontrado en la primera posición de la cadena del alfabeto "AAABC", a la siguiente posición, donde hay otra A.

De modo que el cifrado el incorrecto.

Quizás no debería aceptar cadenas que contengan símbolos repetidos. Pero en el caso de hacerlo, debe mantener un alfabeto de símbolos no deplicados.

**Comment by lauramcastro** [comment]
Este bug report nos lleva a una interesante discusión sobre la especificación.

En la especificación actual, no restringe los alfabetos con símbolos repetidos. Por tanto, en el ejemplo que pones, el cifrado "AC" como resultado para la cadena "AB" con desplazamiento 1 es un resultado válido. Ojo, también lo sería el resultado "BC", como bien indicas. De hecho, "matemáticamente hablando", el conjunto de resultados aceptables sería: "AC", "AC" y "BC".

La pregunta es, como bien planteas, ¿deberíamos permitir un alfabeto con símbolos repetidos, siendo conscientes (si no lo éramos antes) de que conlleva una ambigüedad que permite diferentes implementaciones, con diferentes salidas aceptables ante una misma llamada?

Imaginaos que aceptamos mantener la especificación, con la ambigüedad que conlleva. Cuando un software no tiene una salida aceptable única, las pruebas deben reflejar esto, y aceptar cualquiera de las salidas que se consideren válidas. Si esas salidas válidas son computables, pueden escribirse manualmente las pruebas unitarias necesarias para contemplarlas. Si no son computables a priori, las pruebas basadas en propiedades suelen ser una buena alternativa. Dicho de otro modo, si no fuésemos capaces de calcular todas las posibles salidas válidas (imaginaos un alfabeto muy grande con muchos símbolos repetidos), deberíamos caracterizar la salida de otro modo para poder decidir si es válida o no. Por ejemplo, podríamos intentar cifrar la salida con un offset complementario y comprobar si obtenemos la misma entrada original (en ausencia de un método "descifrar" explícito).

Conclusión: en este caso, no vamos a considerar el comportamiento un bug; @rodarima debes escribir las pruebas apropiadas para validarlo.

**Comment by lauramcastro** [comment]
Re-etiqueto el issue como "question" -para reflejar la discusión sobre la especificación- y lo cierro.
