### ISSUE TITLE
El proceso que realiza la tarea, no comunica siempre su resultado

### ISSUE THREAD

**Issue by rodarima** [lauramcastro/practicas-VVS#5]
Informo del siguiente comportamiento inesperado:

En las tareas, es posible especificar una entrada inconsistente, que provoca que la tarea falle, y nunca se comunique el error de vuelta. Parece debido a que la tarea se lleva a cabo en un proceso en segundo plano, y si este termina de forma inesperada el error no regresa.

He tratado de realizar un test que recoja la excepción, pero `catch` no parece servir.

Esto ocurre en principio tanto como para la tarea del cifrado césar, como para el resto.

    > l(cifrado_cesar).
    {module,cifrado_cesar}
    2> {T,P}=cifrado_cesar:programar(1, "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ", "a", 2).
    {cifrado_cesar,<0.36.0>}
    3> catch cifrado_cesar(P).
    =ERROR REPORT==== 17-May-2015::19:31:01 ===
    Error in process <0.36.0> with exit value: {{badmatch,{error,character_not_in_alphabet}},[{cifrado_cesar,loop,4,[{file,"src/cifrado_cesar.erl"},{line,81}]}]}

Aqui la tarea falla, y no se comunica, por lo que se queda esperando.

De igual modo, todas las tareas fallan cuando se trata de escribir sobre un fichero de salida en el cual no se tienen permisos de escritura. No existe un test para este posible bug, pues no conozco la forma de atrapar la excepción.

    $ ls -la
    -r--r--r-- 1 rodrigo rodrigo     0 may 18 21:57 output-666.dat

La tarea primos:

    $ erl -pa ebin                    
    Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

    Eshell V6.4  (abort with ^G)
    1> l(primos).
    {module,primos}
    2> {T,P}=primos:programar(666,100).
    {primos,<0.36.0>}
    3> primos:do(P).

    =ERROR REPORT==== 18-May-2015::21:59:36 ===
    Error in process <0.36.0> with exit value: {{badmatch,{error,eacces}},[{primos,loop,2,[{file,"src/primos.erl"},{line,85}]}]}

El filtro blanco-negro:

    $ erl -pa ebin
    Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

    Eshell V6.4  (abort with ^G)
    1> l(filtro_bn).
    {module,filtro_bn}
    2> {T,P}=filtro_bn:programar(666, "test/unidad/tareas/1-pixel.png").
    {filtro_bn,<0.36.0>}
    3> filtro_bn:do(P).
    Transforming (average) each pixel of (1 x 1 image): 4

    =ERROR REPORT==== 18-May-2015::22:02:27 ===
    Error in process <0.36.0> with exit value: {{badmatch,{error,eacces}},[{filtro_bn,loop,2,[{file,"src/filtro_bn.erl"},{line,90}]}]}

La tarea de cifrado cesar:

    $ erl -pa ebin
    Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

    Eshell V6.4  (abort with ^G)
    1> l(cifrado_cesar).
    {module,cifrado_cesar}
    2> {T,P}=cifrado_cesar:programar(666,"ACB","A",1).
    {cifrado_cesar,<0.39.0>}
    4> cifrado_cesar:do(P).

    =ERROR REPORT==== 18-May-2015::22:09:07 ===
    Error in process <0.39.0> with exit value: {{badmatch,{error,eacces}},[{cifrado_cesar,loop,4,[{file,"src/cifrado_cesar.erl"},{line,84}]}]}

**Comment by lauramcastro** [comment]
Gracias por detectar e informar de este bug, @rodarima 

El comportamiento anómalo consiste en que la función `programar` de cada tarea crea un proceso que se queda esperando, con la tarea (sea cual sea) lista para ser ejectuada, a que alguien le dé luz verde (llamando a `do/0`).

Ahora bien, si el proceso que va a ejecutar la tarea muere durante la ejecución de la misma, el proceso que está llamando a `do/0` nunca recibe respuesta (podéis ver que, por ejemplo, en https://github.com/lauramcastro/practicas-VVS/blob/master/src/cifrado_cesar.erl#L68, se entra en un `receive` del que nunca se saldrá ya que al no terminar, el proceso que ejecuta la tarea nunca llega a avisar de que ha acabado (lo que en circunstancias normales hace antes de finalizar su ejecución: https://github.com/lauramcastro/practicas-VVS/blob/master/src/cifrado_cesar.erl#L85).

Cuando el proceso que ha llamado a `do/0` es el shell, el no recibir nunca respuesta provoca el bloqueo del terminal. Cuando el proceso que está llamando a `do/0` es una prueba, la prueba acaba por fallar con un `timeout` (que no se cataloga ni como fallo ni como skipped ni como
passed), de manera parecida a como ocurría con la prueba no funcional mencionada en el issue #6 .

Se propone como solución que el método `do/0` falle con un {error, Msg} cuando el proceso que debe realizar la tarea muere de manera anormal. Esto en Erlang puede detectarse creando un link entre dos procesos, lo que hace que, si uno muere, el otro recibe un mensaje avisándole. Podéis ver la implementación correspondiente en el commit XXX, donde se ha añadido este comportamiento a todas las tareas concretas.

Puedes informar de este comportamiento (que es común a todas las
tareas, pero nadie ha dicho nada aún al respecto) en el repositorio, y
discutimos cómo solucionarlo :-).
