### ISSUE TITLE
Problema con falsos duplicados

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#7]
Se ha detectado que si en el almacén ya se había agregado uno de los contenidos de "Amy winehouse", no se puede añadir ninguno más, ya que salta el error de contenido duplicado, aunque realmente no se encuentre ese contenido en el almacén.

**Comment by hmiacatracha** [comment]
En la pestaña "Contenidos" cuando queremos agregar contenido realizamos los siguientes pasos:

1.- Elegimos el almacén, en donde  al que queremos añadir el contenido. En nuestro caso hemos elegido el almacen "Sony BMG Music" 
2.- Seleccionamos el contenido "Amy Winehouse: Rehab" y le damos al botón "Agregar contenido", como resultado se añade el contenido al almacén. 
3.- Seleccionamos el contenido "Avril Lavigne: Greatest Hits"  y le damos el botón  "Agregar contenido" , como resultado se añade el contenido al almacén. 

4.- Realizamos la misma acción que en los ultimos dos pasos pero con el contenido "Amy Winehouse: Rehab con bonus (Coldplay: Singles)"  y nosotros esperamos que se añada el contenido al almacén sin ningún problema, pero sin embargo nos envía un mensaje de error "Contenido duplicado"

**Comment by lauramcastro** [comment]
El comportamiento es el esperado, ya que un contenido se considera el mismo siempre que el `ArchivoAudio` de base sea el mismo, aunque haya sido decorado. El diseño de los `Contenido`s incluye la posibilidad de decorarlos (patrón Decorador) con un contenido de `Bonus` (que es el caso que habéis detectado) o con un contenido de `Promocion`.

Entre los escenarios de prueba de este subsistema, por tanto, debería haber casos que verifiquen que, efectivamente, cualquier combinación de comparaciones que hagamos de `Contenido`s con o sin `Bonus`es o `Promocion`es adjuntas, se consideran el mismo contenido si el `ArchivoAudio` que decoran es el mismo.

Cierro esta issue como inválida, aunque podríamos decir que la especificación estaba incompleta porque este no estaba indicado en ningún sitio :-). Voy a añadir esta explicación al README, y si la implementación respeta o no esta especificación más completa, tendréis que comprobarlo implementando las pruebas correspondientes.
