### ISSUE TITLE
¿Un almacén se puede proveer a si mismo?

### ISSUE THREAD

**Issue by AdriGL** [lauramcastro/practicas-VVS#9]
Si se intenta poner a un almacén como proveedor de si mismo, la aplicación lo hace. ¿Esto es un bug o realmente se puede hacer?

**Comment by lauramcastro** [comment]
La funcionalidad de que un almacén tenga otro como proveedor no la tienen todos los almacenes. Está diseñada e implementada con un patrón Decorador, de manera que sólo los almacenes que se decoren con un `ProveedorAlmacen` tendrán un proveedor.

**Comment by AdriGL** [comment]
Reabro el issue ya que hay que realizar las pruebas en las que se demuestre que no se modifica el estado de un almacen, si no esta decorado como proveedor, pero se le intenta establecer uno.

**Comment by AdriGL** [comment]
El commit  8d60bc9 añade las pruebas que comprueban que no se modifica el estado de un almacén real si se intenta establecer un proveedor. Falta realizar esta prueba en el resto de almacenes, las cuales se añadirán cuando se solucionen los issues abiertos que indican la simplificación de esos tests (issue #20 , #21 y #22 )
